from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from typing import Any, Dict, List, Optional


@dataclass
class Plan:
    intent: str
    command: str
    shell: str
    risk: str
    assumptions: List[str] = field(default_factory=list)
    tools: List[str] = field(default_factory=list)
    clarification: Optional[str] = None

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


class PlanError(ValueError):
    pass


def extract_json_object(content: str) -> Dict[str, Any]:
    text = content.strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    start = text.find("{")
    end = text.rfind("}")
    if start < 0 or end <= start:
        raise PlanError("模型响应中没有找到 JSON 计划")
    try:
        value = json.loads(text[start : end + 1])
    except json.JSONDecodeError as exc:
        raise PlanError(f"模型计划 JSON 无效：{exc}") from exc
    if not isinstance(value, dict):
        raise PlanError("模型计划必须是 JSON object")
    return value


def parse_plan(content: str, platform: str, language: str) -> Plan:
    value = extract_json_object(content)
    clarification = value.get("clarification")
    if isinstance(clarification, str) and clarification.strip():
        return Plan(
            intent=str(value.get("intent") or "clarify"),
            command="",
            shell=str(value.get("shell") or default_shell(platform)),
            risk="read_only",
            clarification=clarification.strip(),
        )
    command = value.get("command")
    if not isinstance(command, str) or not command.strip():
        raise PlanError("模型没有返回可执行命令，也没有提出澄清问题")
    command = command.strip()
    if any(char in command for char in ("\0", "\n", "\r")):
        raise PlanError("模型命令包含不允许的控制字符")
    shell = str(value.get("shell") or default_shell(platform))
    if not shell_supported(platform, shell):
        raise PlanError(f"模型返回了不匹配的平台 Shell `{shell}`（当前平台为 {platform}）")
    declared = normalize_risk(value.get("risk"))
    risk = max_risk(declared, assess_command_risk(command))
    assumptions = [str(item) for item in value.get("assumptions", []) if isinstance(item, str)]
    if not assumptions:
        assumptions = ["命令由模型生成，执行前请检查目标和参数" if language == "zh" else "The command was generated by a model; review its target and arguments before execution."]
    tools = [str(item) for item in value.get("tools", []) if isinstance(item, str)] or ["shell"]
    return Plan(
        intent=str(value.get("intent") or "model.command"),
        command=command,
        shell=shell,
        risk=risk,
        assumptions=assumptions,
        tools=tools,
    )


def normalize_risk(value: Any) -> str:
    normalized = str(value or "high").strip().lower()
    if normalized in {"read_only", "readonly", "read-only"}:
        return "read_only"
    if normalized in {"write", "modify"}:
        return "write"
    return "high"


def max_risk(left: str, right: str) -> str:
    ranks = {"read_only": 0, "write": 1, "high": 2}
    return left if ranks[left] >= ranks[right] else right


def assess_command_risk(command: str) -> str:
    lower = command.lower()
    high = ("rm -rf", "rm -r ", "remove-item -recurse", "format ", "format-volume", "mkfs", "dd if=", "diskpart", "git reset --hard", "sudo ", "shutdown", "reboot", "curl ", "wget ")
    if any(marker in lower for marker in high):
        return "high"
    write = (" > ", " >> ", "mkdir", "touch ", "cp ", "mv ", "new-item", "set-content")
    return "write" if any(marker in lower for marker in write) else "read_only"


def default_shell(platform: str) -> str:
    return "powershell" if platform == "windows" else "sh"


def shell_supported(platform: str, shell: str) -> bool:
    shell = shell.lower()
    if platform == "windows":
        return "powershell" in shell or shell == "pwsh"
    return any(shell == name or shell.endswith("/" + name) for name in ("sh", "bash", "zsh", "fish"))
